version: '2'
services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - etc:/etc/prometheus/
      - data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    labels:
      service: prometheus
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
    - alertmanager_etc:/etc/alertmanager/
    - alertmanager_data:/alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    labels:
      service: alertmanager
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '-collector.procfs=/host/proc -collector.sysfs=/host/sys -collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file: ${PWD}/.env
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name


volumes:
  etc:
    driver: "local"
  data:
    driver: "local"
  alertmanager_etc:
    driver: "local"
  alertmanager_data:
    driver: "local"

