version: '2'
services:

  prometheus:
    scale: 1
    start_on_create: true
    health_check:
      port: 9090
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000
      request_line: GET "/" "HTTP/1.0"

  alertmanager:
    scale: 1
    start_on_create: true
    health_check:
      port: 9093
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000

  node-exporter:
    scale: 1
    start_on_create: true
    health_check:
      port: 9100
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000

  cadvizor:
    scale: 1
    start_on_create: true
    health_check:
      port: 8080
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000

  mysqld-exporter:
    scale: 1
    start_on_create: true
    health_check:
      port: 9104
      interval: 60000
      initializing_timeout: 60000
      reinitializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000
